# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Program')),
            ],
        ),
    ]
