# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0002_timedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedata',
            name='program',
        ),
    ]
