# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0004_auto_20170102_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeofprogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=200)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Program')),
            ],
        ),
        migrations.RemoveField(
            model_name='time_data',
            name='program',
        ),
        migrations.DeleteModel(
            name='Time_Data',
        ),
    ]
