# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0005_auto_20170102_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofprogram',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
