# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0006_timeofprogram_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeofprogram',
            old_name='t',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='timeofprogram',
            name='date',
        ),
    ]
