# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0007_auto_20170102_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofprogram',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='timeofprogram',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
