# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0008_auto_20170102_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeofprogram',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
    ]
