# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0010_auto_20170102_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeofprogram',
            name='comment',
        ),
    ]
