# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0011_remove_timeofprogram_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('o', 'Others')], default='o', max_length=200)),
            ],
        ),
    ]
