# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0012_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
