# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0013_employee_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('MGR', 'Manager'), ('REC', 'Receptionist'), ('TEC', 'Tech'), ('PH', 'Photographer'), ('ASS', 'Assistence')], default='ASS', max_length=200)),
                ('work', models.TextField()),
                ('salary_per_hour', models.IntegerField(default=0)),
            ],
        ),
    ]
