# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0014_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('MGR', 'Manager'), ('REC', 'Receptionist'), ('TEC', 'Tech'), ('PH', 'Photographer'), ('ASS', 'Assistence')], default='ASS', max_length=200)),
                ('working_hours', models.DurationField(default=datetime.timedelta(0, 3600))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Employee')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Program')),
            ],
        ),
    ]
