# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0015_works_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('buying_date', models.DateField(default=datetime.date.today)),
                ('work', models.TextField(blank=True)),
            ],
        ),
    ]
