# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0016_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('N', 'Normal'), ('S', 'Student'), ('D', 'Discount')], default='N', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Program')),
            ],
        ),
        migrations.RenameModel(
            old_name='timeofprogram',
            new_name='Time_of_program',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='work',
            new_name='condition',
        ),
    ]
