# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0017_auto_20170102_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Equipment')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Program')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Student', 'Student'), ('Discount', 'Discount')], default='Normal', max_length=200),
        ),
    ]
