# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0020_auto_20170102_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perform',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='perform',
            name='program',
        ),
        migrations.DeleteModel(
            name='Perform',
        ),
        migrations.DeleteModel(
            name='Performer',
        ),
    ]
