# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0021_auto_20170102_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='perform',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Performer'),
        ),
        migrations.AddField(
            model_name='perform',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Program'),
        ),
    ]
