# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0023_auto_20170102_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('MC', 'Music'), ('SP', 'Speech'), ('PT', 'Photo')], default='MC', max_length=200)),
                ('salary_per_month', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Employee')),
            ],
        ),
        migrations.RenameField(
            model_name='program',
            old_name='ptype',
            new_name='program_type',
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together=set([('employee', 'program_type')]),
        ),
    ]
