# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0026_auto_20170102_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='program_type',
            field=models.CharField(choices=[('Music', 'Music'), ('Speech', 'Speech'), ('Photo', 'Photo'), ('Drama', 'Drama')], default='Music', max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Music', 'Music'), ('Speech', 'Speech'), ('Photo', 'Photo'), ('Drama', 'Drama')], default='Music', max_length=200),
        ),
    ]
