# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0028_auto_20170102_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='job_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='program',
            name='program_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
