# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0030_auto_20170115_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works_on',
            name='job_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Technician', 'Technician'), ('Photographer', 'Photographer'), ('Assistence', 'Assistence')], default='Assistence', max_length=200),
        ),
    ]
