# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0032_auto_20170115_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_photo',
        ),
    ]
