# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0034_auto_20170115_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='works_on',
            name='job_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Technician', 'Technician'), ('Photographer', 'Photographer'), ('Assistence', 'Assistence')], default='Assistence', max_length=200),
        ),
    ]
