# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0036_auto_20170115_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], default='others', max_length=200),
        ),
    ]
