# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0037_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_photo',
        ),
    ]
