# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0038_remove_job_job_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
