# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0039_job_job_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_name',
            new_name='equipment_type',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='buying_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_per_hour',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='manager',
            name='salary_per_month',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='performer',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='performer',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='audience_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='comment',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='works_on',
            name='working_hours',
            field=models.DurationField(blank=True, default=datetime.timedelta(0, 3600)),
        ),
    ]
