# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcenter', '0040_auto_20170115_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Technician', 'Technician'), ('Photographer', 'Photographer'), ('Assistence', 'Assistence')], default='Assistence', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='works_on',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcenter.Job'),
        ),
    ]
